export enum UserRoles {
   ADMIN = 'ROLE_ADMIN',
   SERVICE_OWNER = 'ROLE_SERVICE_OWNER',
   SOLUTION_ARCHITECT = 'ROLE_SOLUTION_ARCHITECT',
   SERVICE_PUBLISHER = 'ROLE_SERVICE_PUBLISHER',
   TECH_PUBS = 'ROLE_TECH_PUBS',
   ITVM_DATA_ADMIN = 'ROLE_ITVM_DATA_ADMIN',
   DWJM_DATA_ADMIN = 'ROLE_DWJM_DATA_ADMIN',
   CONSULTANT = 'ROLE_CONSULTANT',
   STOREFRONTS_DATA_READ_ONLY = 'ROLE_STOREFRONTS_DATA_READ_ONLY',
   SALES_MANAGEMENT = 'ROLE_SALES_MANAGEMENT',
   PSO_MANAGEMENT = 'ROLE_PSO_MANAGEMENT',
   CORE_SALES = 'ROLE_CORE_SALES',
   SERVICES_SALES = 'ROLE_SERVICES_SALES',
   PROJECT_MANAGER = 'ROLE_PROJECT_MANAGER'
}